# Generated by Django 4.1.4 on 2023-09-28 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_address', models.CharField(max_length=255)),
                ('envs', models.JSONField()),
                ('command', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containerizer.app')),
            ],
        ),
        migrations.CreateModel(
            name='RunningHistoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Finished', 'Finished')], max_length=255)),
                ('envs', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('container_id', models.ForeignKey(db_column='container_id', on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='containerizer.container', to_field='container_id')),
            ],
        ),
    ]
