# Generated by Django 4.1.4 on 2023-09-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containerizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runninghistoryrecord',
            old_name='container_id',
            new_name='container',
        ),
    ]
