# Generated by Django 4.1.4 on 2023-09-28 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containerizer', '0002_rename_container_id_runninghistoryrecord_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='containerizer.app'),
        ),
    ]
