# Generated by Django 4.1.4 on 2023-09-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containerizer', '0003_alter_container_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='command',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='envs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
