# Generated by Django 4.1.4 on 2023-09-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containerizer', '0004_alter_app_command_alter_app_envs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runninghistoryrecord',
            name='envs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
