# Generated by Django 4.1.4 on 2023-09-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containerizer', '0005_alter_runninghistoryrecord_envs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='command',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['id'], name='containeriz_id_398c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['container_id'], name='containeriz_contain_e0d448_idx'),
        ),
        migrations.AddIndex(
            model_name='runninghistoryrecord',
            index=models.Index(fields=['container_id'], name='containeriz_contain_9fb146_idx'),
        ),
    ]
