# Generated by Django 4.1.4 on 2023-09-30 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containerizer', '0006_alter_app_command_app_containeriz_id_398c6d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='command',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None),
        ),
    ]
