# Generated by Django 4.1.4 on 2023-09-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containerizer', '0007_alter_app_command'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='app',
            name='containeriz_id_398c6d_idx',
        ),
    ]
