# Generated by Django 4.1.4 on 2023-09-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containerizer', '0008_remove_app_containeriz_id_398c6d_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='app',
            index=models.Index(fields=['id'], name='containeriz_id_398c6d_idx'),
        ),
    ]
